# Generated by Django 5.0.4 on 2024-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
