# Generated by Django 5.0.4 on 2024-04-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_company_logo_customer_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='subscribe_date',
            new_name='subscribtion_date',
        ),
    ]
