# Generated by Django 5.0.4 on 2024-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_subscribe_date_customer_subscribtion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
    ]
