# Generated by Django 5.0.4 on 2024-05-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='custom_price',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
