# Generated by Django 5.0.4 on 2024-04-14 12:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_show', models.BooleanField(default=True)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_show', models.BooleanField(default=True)),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_show', models.BooleanField(default=True)),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_show', models.BooleanField(default=True)),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end', models.TimeField(default=datetime.time(17, 0))),
                ('friday_show', models.BooleanField(default=True)),
                ('friday_start', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_show', models.BooleanField(default=True)),
                ('saturday_start', models.TimeField(default=datetime.time(9, 0))),
                ('saturday_end', models.TimeField(default=datetime.time(17, 0))),
                ('sunday_show', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(default=datetime.time(9, 0))),
                ('sunday_end', models.TimeField(default=datetime.time(17, 0))),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('salary', models.FloatField()),
                ('salary_start_date', models.DateTimeField(auto_now_add=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeecategory')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeschedule')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('salary_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
        ),
    ]
