# Generated by Django 5.0.4 on 2024-04-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_schedule_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='join_date',
        ),
    ]
